### ISSUE TITLE
DD_API_KEY environment variable ignored by the container

### ISSUE THREAD

**Issue by ain** [DataDog/docker-compose-example#17]
## Steps to reproduce

1. Run Docker Compose with the following service:

```yaml
  datadog:
    image: datadog/agent:latest
    links:
      - service1
      - service2
      - service3
    environment:
      - DD_APY_KEY=<disclosed>
      - DD_SITE=datadoghq.eu
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
```

## What happens?

```
app-engine-datadog-1  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
app-engine-datadog-1  | [s6-init] ensuring user provided files have correct perms...exited 0.
app-engine-datadog-1  | [fix-attrs.d] applying ownership & permissions fixes...
app-engine-datadog-1  | [fix-attrs.d] done.
app-engine-datadog-1  | [cont-init.d] executing container initialization scripts...
app-engine-datadog-1  | [cont-init.d] 01-check-apikey.sh: executing... 
app-engine-datadog-1  | 
app-engine-datadog-1  | ==================================================================================
app-engine-datadog-1  | You must set an DD_API_KEY environment variable to run the Datadog Agent container
app-engine-datadog-1  | ==================================================================================
app-engine-datadog-1  | 
app-engine-datadog-1  | [cont-init.d] 01-check-apikey.sh: exited 1.
app-engine-datadog-1  | [cont-finish.d] executing container finish scripts...
app-engine-datadog-1  | [cont-finish.d] done.
app-engine-datadog-1  | [s6-finish] waiting for services.
app-engine-datadog-1  | [s6-finish] sending all processes the TERM signal.
app-engine-datadog-1  | [s6-finish] sending all processes the KILL signal and exiting.
app-engine-datadog-1 exited with code 1
```

## What should happen?

Service should not fail over missing `DD_API_KEY` environment variable since it is defined.
